kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
